- become: yes
  hosts: all
  remote_user: ubuntu
  gather_facts: no
  become: yes
  vars_files:
    - ./vars/external_vars.yml
  name: agent configure
  tasks:
  - name: Add the user
    ansible.builtin.user:
      name: "{{item.name}}"
      shell: /bin/bash
      state: "{{ item.state}}"
    with_items: 
         -  "{{ users }}"
  - name: Set authorized key taken from file
    authorized_key:
        user: "{{item.name}}"
        state: "{{item.state}}"
        key: "{{ lookup('file', 'public-ssh/{{item.name}}.pub') }}"
    with_items: 
       -  "{{ users }}"
    when:  item.state == "present"

  
