name: create user
on:
  push:
    branches:
      - ssh-tunnel     

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
   
        
      - name: Run playbook
        uses: dawidd6/action-ansible-playbook@v2
        with:
          # Required, playbook filepath
          playbook: users.yaml
          # Optional, directory where playbooks live
          directory: ansible_database_user/
          # Optional, SSH private key
          key: ${{secrets.SSH_PRIVATE_KEY}}
          # Optional, literal inventory file contents
          # Optional, additional flags to pass to ansible-playbook
          options: |
            --inventory inventory
